-- Read the docs: https://www.nvoid.org/configuration
-- Video Tutorials: https://www.youtube.com/watch?v=sFA9kX-Ud_c&list=PLhoH5vyxr6QqGu0i7tt_XoVK9v-KvZ3m6
-- Forum: https://www.reddit.com/r/nvoid/
-- Discord: https://discord.com/invite/Xb9B4Ny
