vim.defer_fn(function()
  pcall(require, "impatient")
end, 0)
require("nvoid.core.autocmd")
require("nvoid.core.command")
require("nvoid.core.options")
require("nvoid.core.map")
pcall(require, "custom.nvoidrc")
require("nvoid.core.packer").load()
