return {
  lsp = {
    error = " ",
    warn = " ",
    hint = " ",
    info = "",
    debug = "",
  },
  git = {
    added = "  ",
    modified = "柳",
    removed = " ",
  },
  statusline = {
    lsp = "  ",
    treesitter = "",
  },
  cmp = {
    Class = " ",
    Color = " ",
    Constant = "ﲀ ",
    Constructor = " ",
    Enum = "練",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = "",
    Folder = " ",
    Function = " ",
    Interface = "ﰮ ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Operator = "",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = "塞",
    Value = " ",
    Variable = " ",
  },
  bufferline = {
    indicator = "▎",
    buffer_close = "",
    modified = "●",
    close = "",
    left_marker = "",
    right_marker = "",
  },
  nvimtree = {
    default = "",
    symlink = "",
    folder = {
      arrow_open = "",
      arrow_closed = "",
      default = "",
      open = "",
      empty = "",
      empty_open = "",
      symlink = "",
      symlink_open = "",
    },
    git = {
      unstaged = "",
      staged = "S",
      unmerged = "",
      renamed = "➜",
      untracked = "U",
      deleted = "",
      ignored = "◌",
    },
  },
  telescope = {
    prompt_prefix = "   ",
  },
  whick_key = {
    breadcrumb = "» ",
    separator = "➜ ",
    group = "+ ",
  },
  borders = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
}
