require("plugins/config/icons-config")
require("plugins/config/statusline")
require("plugins/config/bufferline")
require("plugins/config/indentline")
require("plugins/config/colorizer")
require("plugins/config/git")
require("plugins/config/treesitter")
-- require("plugins/config/lsp")
-- require("plugins/config/lsp/installer")
require("plugins/config/cmp")
require("plugins/config/autopairs")
require("plugins/config/dashboard")
require("plugins/config/nvimtree")
require("plugins/config/telescope")
require("plugins/config/term")
require("plugins/config/which-key")
