local theme = require("nvoid.builtin.base16").get_theme_tb "base_30"

return {
  TSAnnotation = { fg = theme.blue },
  TSAttribute = { fg = theme.cyan },
  TSConstructor = { fg = theme.yellow },
  TSType = { fg = theme.yellow },
  TSTypeBuiltin = { fg = theme.yellow },
  TSConditional = { fg = theme.dark_purple },
  TSException = { fg = theme.purple },
  TSInclude = { fg = theme.purple },
  TSKeyword = { fg = theme.dark_purple },
  TSKeywordReturn = { fg = theme.dark_purple },
  TSKeywordFunction = { fg = theme.dark_purple },
  TSLabel = { fg = theme.blue },
  TSNone = { fg = theme.white },
  TSNamespace = { fg = theme.purple },
  TSRepeat = { fg = theme.purple },
  TSConstant = { fg = theme.yellow },
  TSConstBuiltin = { fg = theme.orange },
  TSFloat = { fg = theme.orange },
  TSNumber = { fg = theme.yellow },
  TSBoolean = { fg = theme.yellow },
  TSCharacter = { fg = theme.green },
  TSError = { fg = theme.error_red },
  TSFunction = { fg = theme.blue },
  TSFuncBuiltin = { fg = theme.blue },
  TSMethod = { fg = theme.blue },
  TSConstMacro = { fg = theme.cyan },
  TSFuncMacro = { fg = theme.blue },
  TSProperty = { fg = theme.cyan },
  TSOperator = { fg = theme.dark_purple },
  TSField = { fg = theme.blue },
  TSParameter = { fg = theme.red },
  TSParameterReference = { fg = theme.red },
  TSVariable = { fg = theme.white },
  TSVariableBuiltin = { fg = theme.red },
  TSSymbol = { fg = theme.cyan },
  TSText = { fg = theme.white },
  TSTextReference = { fg = theme.red },
  TSPunctDelimiter = { fg = theme.white },
  TSTagDelimiter = { fg = theme.grey },
  TSTagAttribute = { fg = theme.orange },
  TSPunctBracket = { fg = theme.white },
  TSPunctSpecial = { fg = theme.white },
  TSString = { fg = theme.green },
  TSStringRegex = { fg = theme.orange },
  TSStringEscape = { fg = theme.orange },
  TSTag = { fg = theme.blue },
  TSEmphasis = { italic = true },
  TSUnderline = { underline = true },
  TSNote = { fg = theme.yellow, bold = true },
  TSWarning = { fg = theme.orange, bold = true },
  TSDanger = { fg = theme.red, bold = true },
  TSTitle = { fg = theme.blue },
  TSLiteral = { fg = theme.green },
  TSURI = { fg = theme.blue },
  TSMath = { fg = theme.white },
  TSKeywordOperator = { fg = theme.purple },
  TSStructure = { fg = theme.white },
  TSStrong = { fg = theme.yellow },
  TSQueryLinterError = { fg = theme.orange },
  TSEnvironment = { fg = theme.white },
  TSEnvironmentName = { fg = theme.white },
}
